services:
  backend:
    build: .
    ports:
      - 8080:80
    volumes:
      - ${PWD}:/src:ro
      - ${PWD}/etc/air.toml:/air.toml:ro
    networks:
      - database
    env_file: .env
    depends_on:
      - db
  db:
    image: "postgres:14.17"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ${PWD}/etc/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ${PWD}/etc/init-db-config.sh:/docker-entrypoint-initdb.d/init-db-config.sh:ro
      - database:/var/lib/postgresql/data
    networks:
      - database

volumes:
  database:

networks:
  database:
    driver: bridge
    attachable: true
